### ISSUE TITLE
大佬好

### ISSUE THREAD

**Issue by just-test-2021** [Rain-Bus/fhmlib#1]
请问一下如何让身份信息一直保活呢 感觉每天重新抓一次过于麻烦了些
另老哥有计划开发一个用于明日预约的码吗

**Comment by wzl20001001** [comment]
Token的授权好像是经过微信官方平台的，暂时不知道它的获取逻辑，因为Token是有过期时间的，不像上个版本的ID可以保活，所以暂时还是需要在用之前抓包。
明日预约倒是可以实现(conf.py中也有明日预约的GraphQL请求体)，但是有的学校有验证码(验证码获取和提交的请求体也在conf.json中)，需要训练模型，可能会有点麻烦，使用OCR也可以，但是成功率会偏低些，倒是也能用(详见verify.py)。实现的话也不会太难，可以看看其中的逻辑。

**Comment by Rain-Bus** [comment]
> 请问一下如何让身份信息一直保活呢 感觉每天重新抓一次过于麻烦了些
> 另老哥有计划开发一个用于明日预约的码吗

Token的授权好像是经过微信官方平台的，暂时不知道它的获取逻辑，因为Token是有过期时间的，不像上个版本的ID可以保活，所以暂时还是需要在用之前抓包。
明日预约倒是可以实现(conf.py中也有明日预约的GraphQL请求体)，但是有的学校有验证码(验证码获取和提交的请求体也在conf.json中)，需要训练模型，可能会有点麻烦，使用OCR也可以，但是成功率会偏低些，倒是也能用(详见verify.py)。实现的话也不会太难，可以看看其中的逻辑。

**Comment by Lynchzhan** [comment]
大佬想问一下 那个设置抢座的时间间隔为什么设置成0.1 就会一直失败呀 意思就是让它一直重试 比如我在6：59：58开启脚本 他就会一直重试 直到选上 但是我发现用while循环没有有 还是会自动跳出

**Comment by Miunangel** [comment]
@Lynchzhan 我现在已经毕业了，没有图书馆账号了，这个项目也已经好久没维护了。自从我去图书馆的API换成了GraphQL之后Token的续期逻辑也改了，Token续期这一块你有需求的话可以自己抓包分析下。如果程序有地方运行错误，你可以在IDE里打断点调试下看看到底是哪部分了出问题，然后根据需要再修改代码就可以了（最好先抓包看下API）。:)

**Comment by Lynchzhan** [comment]
大佬好 图书馆token我已经解决了
就是说我现在想要设置一个循环比如说他选座失败的时候能够一直重试
可是用了while循环 中途还是会退出 我是初学者 没有找到问题在哪里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Miunangel/fhmlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 上午8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Miunangel/fhmlib] 大佬好 (#1)





 
@Lynchzhan 我现在已经毕业了，没有图书馆账号了，这个项目也已经好久没维护了。自从我去图书馆的API换成了GraphQL之后Token的续期逻辑也改了，Token续期这一块你有需求的话可以自己抓包分析下。如果程序有地方运行错误，你可以在IDE里打断点调试下看看到底是哪部分了出问题，然后根据需要再修改代码就可以了（最好先抓包看下API）。:)

**Comment by Lynchzhan** [comment]
就是这个 下面出错之后 不会一直重试了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Miunangel/fhmlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 上午8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Miunangel/fhmlib] 大佬好 (#1)





 
@Lynchzhan 我现在已经毕业了，没有图书馆账号了，这个项目也已经好久没维护了。自从我去图书馆的API换成了GraphQL之后Token的续期逻辑也改了，Token续期这一块你有需求的话可以自己抓包分析下。如果程序有地方运行错误，你可以在IDE里打断点调试下看看到底是哪部分了出问题，然后根据需要再修改代码就可以了（最好先抓包看下API）。:)

**Comment by Miunangel** [comment]
@Lynchzhan 有报错的图片吗？

**Comment by Lynchzhan** [comment]
大佬 就是这个 调试模式我还不会用 我只在你的函数里面加了定时和 while 就是它不会循环重试 然后如果把conf里面的interval和retry_times改成0.1的话 他就会变成第三个图的样子 一直循环打印失败 但是实际没有运行 大佬你可以给一个联系方式吗 抢座太难了 手点都不能抢到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Miunangel/fhmlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 上午8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Miunangel/fhmlib] 大佬好 (#1)





 
@Lynchzhan 有报错的图片吗？

**Comment by Lynchzhan** [comment]
大佬刚刚搜了下调试 看了下调试 执行到这的时候还没问题 到下面直接就退出了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Miunangel/fhmlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 上午8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Miunangel/fhmlib] 大佬好 (#1)





 
@Lynchzhan 有报错的图片吗？

**Comment by Lynchzhan** [comment]
好好 感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Miunangel/fhmlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 上午8:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Miunangel/fhmlib] 大佬好 (#1)





 
@Lynchzhan 你建个临时的QQ群拉发在issue里，我进一下吧。我在issue里都看不到图片。🤣

**Comment by Lynchzhan** [comment]
群号617337902&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Miunangel/fhmlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 上午8:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Miunangel/fhmlib] 大佬好 (#1)





 
@Lynchzhan 你建个临时的QQ群拉发在issue里，我进一下吧。我在issue里都看不到图片。🤣
